apiVersion: apps/v1
kind: Deployment
metadata:
  name: bzlibrary
  namespace: bzlibrary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bzlibrary
  template:
    metadata:
      labels:
        app: bzlibrary
    spec:
      containers:
        - name: bzlibrary
          image: bzlibrary:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/librarydb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bzlibrary-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bzlibrary-secret
                  key: DB_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
